apiVersion: v1
kind: Service
metadata:
  name: "zeus-api"
  labels:
    app.kubernetes.io/instance: "zeus-api"
    app.kubernetes.io/name: "zeus-api"
    app.kubernetes.io/managed-by: "zeus"
spec:
  type: ClusterIP
  ports:
    - port: 9999
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: "zeus-api"
    app.kubernetes.io/name: "zeus-api"

