name: Build Load Simulator Service

on:
  push:
    paths:
      - .github/workflows/load_simulator.yml
      - apps/microservices/load_simulator/**
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  REPO: zeusfyi
  NAME: load-simulator
  TAG: latest
  GOOS: linux
  GOARCH: amd64

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Login to Docker Registry
        run: docker login -u zeusfyi -p ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build And Publish Zeusfyi Load Simulator
        run: |
          depot build \
          -t ${{ env.REPO }}/${{ env.NAME }}:${{ env.TAG}} \
          --platform=${{ env.GOOS }}/${{ env.GOARCH }} \
          --token ${{ secrets.DEPOT_TOKEN }} \
          --provenance=false \
          -f docker/microservices/load_simulator/Dockerfile . --push
